### ISSUE TITLE
botframework-streaming/lib/subscribableStream.d.ts:15:5 - error TS2416: Property '_write' in type 'SubscribableStream' is not assignable to the same property in base type 'Duplex'

### ISSUE THREAD

**Issue by yingzhanguipath** [microsoft/botbuilder-js#1630]
## Versions
What package version of the SDK are you using.

        "botbuilder-adapter-slack": "^1.0.8",
        "botkit": "^4.6.2"

+-- botbuilder-adapter-slack@1.0.8
| +-- botbuilder@4.7.1
| | +-- botbuilder-core@4.7.1
| | | `-- botframework-schema@4.7.1 deduped
| | +-- botframework-connector@4.7.1 deduped
| | +-- botframework-streaming@4.7.1
| +-- botkit@4.6.2 deduped
+-- botkit@4.6.2
| +-- botbuilder@4.7.1 deduped
| +-- botbuilder-dialogs@4.7.1
| | +-- botbuilder-core@4.7.1 deduped
| +-- botframework-connector@4.7.1
| | +-- botframework-schema@4.7.1

What nodejs version are you using

v10.16.0

What os are you using

Windows 10 Pro

## Describe the bug
Build started breaking after I upgraded to botkit v4.6.2 and botbuilder-adapter-slack v1.0.8. 
It worked well with botkit v4.6.1 and botbuilder-adapter-slack v1.0.4.

**Error message:**
node_modules/botframework-streaming/lib/subscribableStream.d.ts:15:5 - error TS2416: Property '_write' in type 'SubscribableStream' is not assignable to the same property in base type 'Duplex'.
  Type '(chunk: any, encoding: string, callback: (error?: Error | null | undefined) => void) => void' is not assignable to type '(chunk: any, encoding: string, callback: (err?: Error | undefined) => void) => void'.
    Types of parameters 'callback' and 'callback' are incompatible.
      Types of parameters 'err' and 'error' are incompatible.
        Type 'Error | null | undefined' is not assignable to type 'Error | undefined'.
          Type 'null' is not assignable to type 'Error | undefined'.

15     _write(chunk: any, encoding: string, callback: (error?: Error | null) => void): void;

## To Reproduce
npm run build

## Expected behavior
Give a clear and concise description of what you expected to happen.
build successfully
